### ISSUE TITLE
Emojis dont work

### ISSUE THREAD

**Issue by DarkDaVinci2** [Chetan3010/EarthX#18]
Hi,
So emojis with : <a:b_yes:1253829721599512577> , dont work. If someone could tell me who to make them work I would really appriciate it. 
Thank you!
![image](https://github.com/user-attachments/assets/4289605b-07cb-40f9-98dd-57c784e311ac)

**Comment by Chetan3010** [comment]
Hey there!

Thanks you for testing my bot and sorry for not mentioning about this, so those emojis won't work unless your bot has access to them.

How to make them work?

You have two options:
1. Upload all emojis to the Discord Developer Portal's bot emojis API. Replace markdown with `config/emojis.js` respective emojis.
2. Alternatively, you can upload the emojis to a server and replace the IDs in the `config/emojis.js` file with the corresponding emoji IDs. Ensure that your bot is in the same server as the emojis you are using.

Checkout emojis folder to get all your emojis. ( please make sure to pull new changes from repo as i have just pushed those changes).

If you still facing some issues feel free to open new issue :)
